### ISSUE TITLE
Postgres complaining about parameters

### ISSUE THREAD

**Issue by onwsk8r** [go-xorm/builder#17]
So the following code:
```go
b := builder.Select("*").From("day").Where(builder.Eq{"symbol": ticker}).And(builder.Gt{"date": dates[0]})
query, args, err := b.ToSQL()
```
produces the following sql: `SELECT * FROM day WHERE symbol=? AND date>?`, to which Postgres responds `operator does not exist: character varying =?`.

When I rewrite the query to `SELECT * FROM day WHERE symbol= ? AND date> ?` (spaces before the `?`'s), the error changes to `syntax error at or near "AND"`.

However, if I rewrite the query using positional parameters as `SELECT * FROM day WHERE symbol = $1 AND date > $2`, it works.

**Comment by lunny** [comment]
dc8bf48f58fab2b4da338ffd25191905fd741b8f has added support for this. Now you can use `ConvertPlaceholder` to convert `?` to `$1`... see https://github.com/go-xorm/builder/blob/master/builder.go#L194

**Comment by onwsk8r** [comment]
That was fast- you rock! 👍 👍 Thank you!
