### ISSUE TITLE
Why `Builder.limitWriteTo` erase limit condition?

### ISSUE THREAD

**Issue by mythrnr** [go-xorm/builder#40]
When outputting SQL for debugging( using `Builder.ToSQL` ) before executing SQL, only LIMIT and OFFSET conditions were lost.

I looked up and found the following sentence. Why does builder erase `b.limitation` ?
https://github.com/go-xorm/builder/blob/145c9968bfe732a56d7160439d25154c5aaa2f35/builder_limit.go#L23

**Comment by BetaCat0** [comment]
If not, there will be an endless loop. We just make a copy of current ``limit`` conditions for following handling. Futhermore,  you can use ``Bulider.ToBoundSQL`` instead of ``Builder.ToSQL``,  then you'll have a clearer output.

**Comment by mythrnr** [comment]
Thank you for answering. I am glad that it was not a bug.
And thank you for teaching `Builder.ToBoundSQL`. I will use this, or enable `xorm.Engine.showSQL` if needed. :)
