### ISSUE TITLE
Insert argument wrong order

### ISSUE THREAD

**Issue by vit1251** [go-xorm/builder#44]
I write example code

```
	sql, args, err1 := builder.Dialect(builder.MYSQL).
		Insert(builder.Eq{"issue_id": 1, "username": "vit1251", "body": "Hello"}).Into("comment").
		ToSQL()
	log.Printf("sql = %v", sql)
	log.Printf("args = %v", args)
	log.Printf("err1 = %v", err1)
```

my output is

```
sql = INSERT INTO comment (body,issue_id,username) Values (?,?,?)
args = [1 Hello vit1251]
err1 = <nil>
```

As you can see insert order is changes and as result have wrong mapping on insert.

**Comment by vit1251** [comment]
I use version 0.3.2 via go get and does not on master right now.

P.S. May be create unittest for this issue?

**Comment by lunny** [comment]
Have added on #42, see https://github.com/go-xorm/builder/blob/master/builder_insert_test.go#L18. Just tagged v0.3.3, please upgrade.
